apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-deployed-infra
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $.Values.global.namespace }}
    server: https://kubernetes.default.svc
  project: {{ $.Values.global.spec.project }}
  source:
    repoURL: {{ $.Values.global.spec.source.repoURL }}
    targetRevision: {{ if $.Values.cloudDeployedInfra }}
      {{ default .Values.cloudDeployedInfra.targetRevision .Values.global.spec.source.targetRevision }}
    {{ else }}
      {{ .Values.global.spec.source.targetRevision }}
    {{ end }}
    path: charts/argocd-infra/
    helm:
      valueFiles:
        - ./values.yaml
        - ../../clusters/{{ $.Values.global.clusterName }}/infra-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
---
