stfc-cloud-openstack-cluster:
  openstack-cluster:

  # defining the number of control-plane nodes
    controlPlane:
      machineCount: 3

  # defining the number of worker nodes
    nodeGroups:
      - name: default-md-0
        machineCount: 3

  # worker node flavor
    nodeGroupDefaults:
      machineFlavor: l3.nano

  # addon config for the cluster 
  # here we define an nginx ingress controller service
    addons:
      ingress:
        enabled: true
        nginx:
          release:
            values:
              controller:
                service:
                  # create a floatip for ingress on your project and put it here

                  loadBalancerIP: "130.246.211.215" 

      monitoring:
        kubePrometheusStack:
          release:
            values:
              prometheus:
                prometheusSpec:
                  externalLabels:
                    cluster: vicmet
                    env: dev
                ingress:
                  hosts:
                    - prometheus-vicmet.dev.nubes.stfc.ac.uk
                  tls:
                    - hosts:
                        - prometheus-vicmet.dev.nubes.stfc.ac.uk
                      secretName: tls-keypair
              grafana:
                ingress:
                  hosts:
                    - grafana-vicmet.dev.nubes.stfc.ac.uk
                  tls:
                    - hosts:
                        - grafana-vicmet.dev.nubes.stfc.ac.uk
                      secretName: tls-keypair
              alertmanager:
                enabled: false