apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $.Values.global.namespace }}
    server: https://kubernetes.default.svc
  project: {{ $.Values.global.spec.project }}
  source:
    repoURL: {{ $.Values.global.spec.source.repoURL }}
    targetRevision: {{ $.Values.global.spec.source.targetRevision }}
    path: charts/argocd/
    helm:
      valueFiles:
        - ./values.yaml
        - ../../clusters/{{ $.Values.global.clusterName }}/argocd-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
      
    syncOptions:
      - CreateNamespace=true
---
