{{- if ( index $.Values "cert-manager" "enabled" ) }}
# This is deployed as a implicit dependency of the argocd-apps chart
# as it can only be installed once per cluster
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ index $.Values "cert-manager" "namespace" }}
    server: https://kubernetes.default.svc
  project: {{ $.Values.global.spec.project }}
  source:
    repoURL: {{ $.Values.global.spec.source.repoURL }}
    targetRevision: {{ $.Values.global.spec.source.targetRevision }}
    path: charts/apps/cert-manager
    helm:
      valueFiles:
        - ./values.yaml
        - ../../../clusters/{{ $.Values.global.clusterName }}/app-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
{{- end }}