apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-admin-credentials-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
    username: {{ .Values.admin.username }}
    password: {{ .Values.admin.password }}