stfc-cloud-openstack-cluster:
    openstack-cluster:
        clouds:
            openstack:
                auth:
                    auth_url: ENC[AES256_GCM,data:4DDjuyPkxMz1w3i3KLg48Eh23XdVe6GFWa2RdVDTboNinaqKaQ==,iv:OKOqx3Rhm+Le0frQez8hkTCUvv9QRdqJwTa1z82DjXc=,tag:fWQlgb8xgDSfCBmBF1rTGA==,type:str]
                    project_id: ENC[AES256_GCM,data:gNmDP7/M6vXQiLfYiCKn5ZG38XZKETudzRZTIrguYSI=,iv:NxgVDQyjdAOfsVQSKp3NyayViClWwb6PRMxHpXWRaIg=,tag:WUAVm4AbArCndAwetpHBuA==,type:str]
                    application_credential_id: ENC[AES256_GCM,data:bkzlNqNaaU1t0Hmkey1H6SrAMWjRj4fn/dsG+mb2rWI=,iv:3fJhZ8U9V/3wQK8cZKYbfmaKTMp9kKwVrvMGabD+mns=,tag:LB/KgF2znqxI5ubELA3zQg==,type:str]
                    application_credential_secret: ENC[AES256_GCM,data:Db2fgQoxUZJi9IrEQFUINkEemeadOj8V5uMdrZFzJLkKWvQmq6DoMkJtSqnEAnd0HfvyL2SWb41Fff6BTLApk3uOFPY+Mv/zt1zdu2Ey40WD7EFUwW0=,iv:6XnZrA/zmJ2eX9ACNIDEyfzti1FJCgmE42XdgLUPQa0=,tag:TTXBkzm1+hTomCfVJ2hLKA==,type:str]
            region_name: ENC[AES256_GCM,data:s7V5AT83FPTg,iv:8z6chNWrOY5ZY2ijH0gDhYwpoljOeC/gjLWQ/s74FB8=,tag:AMyQBbg3Ve4aZd/33U6+zg==,type:str]
            interface: ENC[AES256_GCM,data:nCjpCOd3,iv:OtldEs9XSfor+4ZKZwYGbknqfpK2irzjIHGAxUo6FGM=,tag:iUNb7DqLukzyoc3yd5bpeg==,type:str]
            identity_api_version: ENC[AES256_GCM,data:gA==,iv:2nqDZmM6Ml/GsaLyudnWYPjsqNX16+xDEvFMJRw2jYk=,tag:1ySShUjlEwJ+wnwd8qQmuA==,type:int]
            auth_type: ENC[AES256_GCM,data:IGVGD3u+bP+k1Y3qLEfJVFs5EafHN4I=,iv:lHSMrGgsRQgwnMecfqB30H8rpXlBx1rOkYZO5IrDldM=,tag:fBqAS7sVjPElCVW2moW3CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr298hh8ammzethfcdeh72c25wnrk3u2zlzxx78k4nfcq2rwpgqs9hljq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVCtNb2JwY2RCMm5Nb1JG
            Smt5YitHTkdqR0U3b2l1Z1R3K24rdFdLVFVrCmt2THRoU2JvSkE3bWVBSzZrbzRY
            NXR4WTlDa3FSYzY1b1o1WWNJeXI0d2sKLS0tIEt6S3RzNTgwTjZKMEpSc1pwSWNP
            ejY5ZGJVSzFjV3p2K1dRWno0YmcxUFUKNukHoWsfue5VHXmmrtuZiLZ6xYTp0NQH
            yD6rjn4ml6knGjkzDJQ5XMdd1XoTLI7oAtI7obj7KhAHj1c4HzcC1A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1acqcungzwkt807d3jt94ngtdt0vhk9kec4ps4a22cpaah57jw4xsl7q4xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVTVSelVrcTQwVHJXUlYw
            cHBLZzlCMGlZT2htdW9NbWxTNmlwL29kQ2owClBBR3U2ZFR4VDUxZEJ3RTNGeUNR
            RFdCcEUrTmVITEthTm5FVUxKZFozd28KLS0tIFVOcyszSFhlYVpQcE1KQUNJYmhL
            ckhBKzdPZjkyL1A5YjZEQ3lBUG1vUmsKzMVjgLlADypTQtgWuRFyWfxoa70Kq/Q4
            qg34v8c3WEzETSDHFuef1q4Ey91mSCtOBrIZ12hwcLt3N6I6ZAPMig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h3dmygqf4v6jg3nxk5sr9jkp27w3q83sqnqxdd5n92xf3w6fs5kshakrxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Q3d3VklxSW8yYTlibWR3
            S1dVa0xWLzRzRHhELzVjajVnazB6UmtYZUNjCnNuaHc5L2dPS0hhWXFxcTlFM0Iv
            YitoMGdJVWtYWGxBMG40ekxMOVA0dHMKLS0tIFUrUGpMMUFZdnl1bXI2cVFBWXBT
            SFdxeEYwYkhxdGdVdHg4ZVRlY1dYa2cK+VmUX4o+Xl7pAaYfzrw+Vs0LgFSaq2+P
            R37inRNA2vAIIW7jzYQhOAUDVlCSoE7DR2gUcCo6jZ6Ol+Ly2pZo0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12khufkd7z25eqgpjjyy0zcrq6kpjxzekmff5zhq7q54tajm4e58qul35x0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSlZ2Q1ZPdHMwQk9YVitK
            REsySDB6b3pLNjZBTjBUZlROYTNvaHQyQmxnCmRvR0FheFIyT3BremdSamhveWlj
            NmwvbVFBallCVjRaaUVYMVZSZnBsRkEKLS0tIE5KanQ4YTBzZWtySFR6MzBuWFE5
            dTErZ0JQSUdrNFVNOWk5ajROSC8rNlEKTY56LUrYh7RLBExiNXO9Tux9BgLMRR4f
            FId8BFraGEN6aCOaKgfSD1YrzBHGvjzHRbjlhQ3l2TPLUYucrlRgkA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16fufeddr0arrns268526gxethxgkh3g0euf8cn37kuwfmq3h23psutz4q8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWjFObEZkOFlLcEVkTzhB
            TzdRQk5Mb1hQTlJCeGtvVHUzQlVQNGtpM0JVCnJCOEtOSjZVdTdpN2pVbEFoQU1n
            SnFzb0dnalg0ZEp4OWhTa3RMYkRtSE0KLS0tIENUam5tSGMrWWtidlJZVGh3aUE3
            TnUva1RId0Zvd2hsVVVYOXV2dHhCeHMK+B1egXyQ81jvOkuKVhquiUC361m+2pa5
            ASSfe7HgVaqRlMU1m8V4sQv3I9Sqzo+/fuboP/nU2yhdjY6aKtK1sA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a8e4gxw67kp27s3hssfxyem3e8jwaha3huz0sttfngeu60pk5pxqkfpg3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM1JGaDAxOVZ2N0ZDUjBz
            Q2JHR2g0TTlwMlpwNlVObFp2Z29iZS9PQnljCmMyVEdCWkV2VCtBNG5EU1RzQ2ov
            aER2eURUMjBzQlg1dVIwUjNXeDVjMVEKLS0tIEtOQXhvdG94aVoyUlk5emNKejhI
            cU9PMWlNUWJTcG5NMDl4M2pabmlmWjgKZRMEVuQEhHKxbC/+xxkBtXgA78atk8u2
            PBdBTB4/9VuL6979U81+wjyK3M0Y1ZodtIYC/5EBH3pyRjklw0zLbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1drky6caal0j2x58yzpw9tyflcpdpmcjqy8nss7zfvspszg0xfpdsyzu8s4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueDhFV1QrUEVOa3RCVm85
            SkpJcFloVWlaTE9VWEtkS0VGTFp1RWl0UFNzCjFJamRoMWdaQ283bFNjdkVNOTU5
            bmRnZG5oM21sMnFZRHZiNk54YkdsY2sKLS0tIEJRbDloUWU0dE1xNDV5bDAyOERn
            RWg0TEZOcDlZRTBMcll5RmtLVkNDY00KwrV5I+Usc0kH0RYNC8dbUKfLBCdcailJ
            lNzwfz8oyZqEc4UfLSiBIWr1ilHY/u8fYtZwT7zNRuc5cJZPmSu/qw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m57vjw60dpr02ghka8kh2xlqsa0ggxauau2y488zdh89vu760qgqh8lcge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN2lOUzU4Z1NHUnZqaTlr
            VW9LaTRnSEI1SjM2c1BMb29Xa3FIdUc1TUJBCmFFNnZhVFVRcXFQN2RkKzdwUGZC
            ZjArVjVXaTZvQVU4LytZU2RxSE13T2MKLS0tIFZ1dlJNOElvcG1aL2ZTVURidzRY
            ZytWNFV3Mm4rMnRHdXdOd3ExdGZYNm8KOjbqmivO2qiodYKTXKVpZm6RHAGdNvsO
            nY/sG2Mm7QmMMWLiSRBAsiYgYugHqhSEh2K7mB7noG6Mai5T3Tc7Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T14:44:35Z"
    mac: ENC[AES256_GCM,data:72PuA6ClJl5VdTfc3d5fbvK+8Rp1tVphWpprZo7YGZxh/PpOhrFPT2y4MMb0/0ncU7C3EK+KI1IhRDA5icdnZ/7W4LccAeWMxq3KioiPgvU8w6uc76bFArnWMn/bI4qeWM6LhSN9eUW148ZuTvhFlgl4wsccYcex58oPCO8Lv9c=,iv:Rw9nY5H9EwhHvQgQon++IDgadMdVLhsPkAc5V9uyJJU=,tag:iV8f8T4UA2fO8NZZgygQxA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.2
