oauth2-proxy:


  extraArgs:
    # limit access to stfc-cloud-dev group
    redirect-url: "https://galaxy.dev.nubes.stfc.ac.uk/oauth2/callback"

galaxy:
  ingress:
    hosts:
    - host: "galaxy.dev.nubes.stfc.ac.uk"
      paths:
        - path: "/"
    tls:
    - hosts:
        - "galaxy.dev.nubes.stfc.ac.uk" 
      secretName: galaxy-tls