oauth2-proxy:
  extraArgs:
    # limit access to stfc-cloud-dev group
    # allowed-group: "stfc-cloud-dev"
    redirect-url: "https://galaxy.dev.nubes.stfc.ac.uk/oauth2/callback"

galaxy:
  configs:
    galaxy.yml:
      galaxy:
        # comma spaced list of admin emails
        admin_users: "anish.mudaraddi@stfc.ac.uk"

  ingress:
    hosts:
    - host: "galaxy.dev.nubes.stfc.ac.uk"
      paths:
        - path: "/"
    tls:
    - hosts:
        - "galaxy.dev.nubes.stfc.ac.uk" 
      secretName: galaxy-tls