apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env }}-cloud-chatops-secrets
type: Opaque
data:
  secrets.yml: |-
    SLACK_BOT_TOKEN: {{ .Values.secrets.slackBotToken }}
    SLACK_APP_TOKEN: {{ .Values.secrets.slackAppToken }}
    GITHUB_TOKEN: {{ .Values.secrets.githubToken }}
