apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env }}-cloud-chatops-secrets
  namespace: {{ .Release.namespace }}
type: Opaque
stringData:
  secrets.yml: |-
    SLACK_BOT_TOKEN: {{ .Values.secrets.slackBotToken }}
    SLACK_APP_TOKEN: {{ .Values.secrets.slackAppToken }}
    GITHUB_TOKEN: {{ .Values.secrets.githubToken }}
