creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    key_groups:
      - age:
          # PSDI Cluster - ArgoCD Access Key (Temporary)
          - age16yjfh7whvhhgkd0rk5zlt6l9lv94j6hzue5yfwc64zaxeml7p3gq58e6sc
          
          # Access Keys
          # Prod Management Access Key
          - age1cq92796c46d06s43t079xc89exe4vd52rh30c9mcafmne62dxyhqrupl4l
