argo-cd:
  global:
    domain: argocd.dev-worker.nubes.stfc.ac.uk

stfc-cloud-longhorn:
  longhorn:
    ingress:
      host: "longhorn.dev-worker.nubes.stfc.ac.uk"
    persistence:
      # can't be set for RWX
      migratable: false