openstack-cluster:

  controlPlane:
    machineCount: 3

  nodeGroups:
    - name: default-md-0
      machineCount: 2

  nodeGroupDefaults:
    machineFlavor: l3.nano
    nodeLabels:	
      # we're running longhorn on this cluster
      # set label so worker nodes can host longhorn volumes
      longhorn.store.nodeselect/longhorn-storage-node: true

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                loadBalancerIP: "130.246.211.106"

    monitoring:
      enabled: true
      lokiStack:
        enabled: false
      kubePrometheusStack:
        release:
          values:
            prometheus:
              prometheusSpec:
                externalLabels:
                  cluster: worker
                  env: dev
              ingress:
                hosts:
                  - prometheus-worker.dev.nubes.stfc.ac.uk
                tls:
                  - hosts: 
                    - prometheus-worker.dev.nubes.stfc.ac.uk
                    secretName: tls-keypair
            grafana:
              ingress:
                hosts:
                  - grafana-worker.dev.nubes.stfc.ac.uk
                tls:
                  - hosts: 
                    - grafana-worker.dev.nubes.stfc.ac.uk
                    secretName: tls-keypair